runtime: go
env: flex
network:
  name: default
  subnetwork_name: default
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "1.21"